version: "4.3.1"
services:
  client:
    build: ../app
    image: weare-app
    container_name: weare-app
    ports: 
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://host.docker.internal:3306/weare
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    name: project-weare
